include ~/.config/sway/catppuccin.conf

exec picom --config ~/.config/picom/picom.conf
exec swaync --config ~/.config/swaync/config.jsonc --style ~/.config/swaync/style.css

set $mod Mod4
set $left h
set $down j
set $up k
set $right l
set $term ghostty
set $menu wofi --show drun
set $filemanager dolphin
set $screenshot hyprshot -h

set $ws1 " "
set $ws2 "󰈹 "
set $ws3 " "
set $ws4 " "
set $ws5 "󱧶 "
set $ws6 "󰠮 "

workspace $ws1
workspace $ws2
workspace $ws3
workspace $ws4
workspace $ws5
workspace $ws6

workspace $ws1

gaps inner 4 
gaps outer 4 

default_border pixel 2.7
default_floating_border pixel 2.7

blur enable
blur_xray enable
blur_radius 3
blur_passes 5
blur_noise 0
blur_brightness 1

default_dim_inactive 0.05

shadows enable
shadow_blur_radius 15

corner_radius 5 
layer_effects "waybar" {
    blur enable;
    blur_xray enable;
    blur_ignore_transparent enable;
    shadows enable;
    corner_radius 10;
}

layer_effects "wofi" {
    blur enable;
    blur_ignore_transparent enable;
    blur_xray enable;
    shadows enable;
    corner_radius 5;
}

# gruvbox
# client.focused #c0a25d #c0a25d #c0a25d #c0a25d

# everforest
#client.focused #a7c080 #a7c080 #a7c080 #a7c080

# nordic
#client.focused #bbc3d4 #d8dee9 #d8dee9 #d8dee9

# catppuccin mocha lavender
client.focused           $lavender $base $text  $lavender $lavender
client.focused_inactive  $overlay0 $base $text  $overlay0 $overlay0
client.unfocused         $overlay0 $base $text  $rosewater $overlay0
client.urgent            $peach    $base $peach $overlay0  $peach
client.placeholder       $overlay0 $base $text  $overlay0  $overlay0
client.background        $base

# ayu mirage
#client.focused #facc6e #facc6e #facc6e #facc6e

# kanagawa wave
#client.focused #7aa89fee #7aa89fee #7aa89fee #7aa89fee
