# прикольно, но для катпучина
# alias ls="exa --tree --level=1 --icons --color=always --no-time --no-user --no-permissions"
alias ls="exa --icons --color=always --group-directories-first --no-time --no-user --no-permissions"
alias cat="bat --theme-dark=base16-256"
alias sudo="doas"
alias ff="fastfetch"
alias nf="neofetch"
alias v="vim"
alias dv="doas vim"
alias nv="nvim"
alias dnv="doas nvim"
alias lg="lazygit"
alias yz="yazi"
alias zshconfig="mate ~/.zshrc"
alias ohmyzsh="mate ~/.oh-my-zsh"
