color=1f1f28
bs-hl-color=dcd7ba
caps-lock-bs-hl-color=dcd7ba
caps-lock-key-hl-color=98bb6c
inside-color=00000000
inside-clear-color=00000000
inside-caps-lock-color=00000000
inside-ver-color=00000000
inside-wrong-color=00000000
key-hl-color=98bb6c
layout-bg-color=00000000
layout-border-color=00000000
layout-text-color=dcd7ba
line-color=00000000
line-clear-color=00000000
line-caps-lock-color=00000000
line-ver-color=00000000
line-wrong-color=00000000
ring-color=957fb8
ring-clear-color=dcd7ba
ring-caps-lock-color=ffa066
ring-ver-color=7fb4ca
ring-wrong-color=c34043
separator-color=00000000
text-color=dcd7ba
text-clear-color=dcd7ba
text-caps-lock-color=ffa066
text-ver-color=7fb4ca
text-wrong-color=c34043
